name: main

on:
  - push
  - pull_request

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2

      - name: Install Cargo
        run: sudo apt install cargo

      - name: Clippy
        run: cargo clippy -- -A clippy::type_complexity -A clippy::module_inception

      - name: Test
        run: cargo test --verbose
